M48
; DRILL file {KiCad (6.0.0)} date Sat Mar 26 23:52:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-26T23:52:22+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.1577Y-4.4138
X6.1577Y-4.6413
T2
X6.0236Y-4.0551
X6.0236Y-5.0
X8.1496Y-4.0551
X8.1496Y-5.0031
T0
M30
